server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Container Name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'docker_container_name'

      # Container ID
      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'docker_container_id'

      # Project Name
      - source_labels: [ '__meta_docker_container_label_com_docker_compose_project' ]
        target_label: 'docker_project_name'

      # Project Service
      - source_labels: [ '__meta_docker_container_label_com_docker_compose_service' ]
        target_label: 'docker_project_service'

  - job_name: systemd_journal
    journal:
      max_age: 12h
      labels:
        job: systemd_journal

    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: [ '__journal__hostname' ]
        target_label: 'hostname'
      - source_labels: [ '__journal_syslog_identifier' ]
        target_label: 'syslog_identifier'
      - source_labels: [ '__journal_priority' ]
        target_label: 'priority'